# Generated by Django 5.0.3 on 2024-03-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('state', models.CharField()),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
